### ISSUE TITLE
Feature Request: Pass Cards freely before the game 

### ISSUE THREAD

**Issue by Valentinbist** [HenriWahl/doko3000#2]
Hello Henri,

thanks for developing this project! Me and my friends would really appreciate a feature similar to "contra re Austausch" but where the exchanged cards can be passed to, and successively exchanged with, any player, regardless of team.
This way a Armut can be played like we used to do it.

Also, there seems to be a hard limit of three cards which can be exchanged, but in our rule set there are cases where 4 cards can be exchanged. We would like this changed to play the good old "Vierer Armut"

**Comment by HenriWahl** [comment]
Interesting concept... Yet Another Funny Doppelkopf Rule.

The easiest solution might be to remove the exchange-with-other-party-member condition and to make the number of exchanged cards configurable.

I can't promise you when this will happen but I've put it onto the todo list. PRs are always welcome too :-)

**Comment by Valentinbist** [comment]
Thanks for the answer.

In our rule set there even can be conditions where each player passes a card to another player in a circle, without seeing the card one gets before choosing a card to pass on. However this is rule we only play, lets say, rather late in the evening when counting points allready stopped. So this feature is not important right now. Generally, such an absolutly free card exchange system would fit into the philosopy of the game quite nice. 

Nevertheless i will look into the code and look into your approach, since it does not seem to need to much changes :)

**Comment by HenriWahl** [comment]
Finally this feature actually exists.

If you still (or again) play Doppelkopf online just give it a try. Latest release 2.4.0 comes with the changes. Also available at Dockerhub: https://hub.docker.com/r/henriwahl/doko3000.

Instead of directly exchanging cards with the own party one can choose now whom to exchange cards with. Players are free to change as much cards as they like but should take care to return the same amount of cards as they received - truly open world card game!

Regards and good luck
